#!/bin/bash
export PATH="/sbin:/bin:/usr/sbin:/usr/bin:/opt/bin:/usr/local/bin"
trapcom() {
sudo rm -rf "$workdir"; exit 0
}
trap trapcom SIGTERM SIGINT
workdir="/usr/local/brcr_updater"
url="https://dl.google.com/dl/edgedl/chromeos/recovery/recovery.conf"
[ -d "$workdir" ] || sudo mkdir -p $workdir
[ -n "$(uname -m | grep "i.*86")" ] && { mode="x86-"; echo "WARNING: your device CPU is x86. This script will download the latest brunch, which is most likely incompatible with x86. Continue? (Press Enter if yes, Ctrl-C if no)"; read; } || mode=
cd $workdir
echo "===> Downloading recovery.conf file"
sudo curl --progress-bar -s -S -L -o $workdir/recovery.conf "$url" || exit 2
board="$(grep "CHROMEOS_RELEASE_DESCRIPTION=.*" "/etc/lsb-release" | rev | cut -d " " -f 1,2 | rev)"
board=$board
board="$(echo $board | cut -d " " -f 1)"
echo "===> Getting latest available release of brunch"
_brunch="$(curl --progress-bar -s -S -L -o - "https://api.github.com/repos/sebanc/brunch/releases/latest")"
brunch="$(echo "$_brunch" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/')"
brunch_url="$(echo "$_brunch" | grep '"browser_download_url":' | sed -E 's/.*"([^"]+)".*/\1/')"
echo "===> Parsing..."
string="$(grep -o "url=.*/chromeos_.*_${mode}${board}_.*.bin\..*" recovery.conf | sort -V | tail -n 1)"
build_num="$(grep -B 12 --max-count 1 "$string" ./recovery.conf | grep -o "version=.*" | cut -d "=" -f 2)"
build_url="$(echo "$string" | cut -d "=" -f 2-)"
cur_version="$(grep "CHROMEOS_RELEASE_VERSION=.*" "/etc/lsb-release" | cut -d "=" -f 2)"
echo "Board name:                "$board""
echo "Latest ChromeOS build:     "$build_num""
echo "Current ChromeOS build:    "$cur_version""
echo "Latest available brunch:   "$brunch""
echo ""
echo -e "Click \e[0;33mEnter\e[0m to continue"
read
echo "===> Downloading brunch $brunch"
sudo curl --progress-bar -s -S -L -o $workdir/$(echo $brunch_url | grep -o "[^/]*$") "$brunch_url"
echo "===> Downloading ChromeOS $build_num"
sudo curl --progress-bar -s -S -L -o "$workdir/chromeos.bin.zip" "$build_url"
echo "===> Unpacking ChromeOS .zip archive..."
sudo unzip "$workdir/chromeos.bin.zip" || exit 2
sudo mv "$workdir/chromeos_"* "$workdir/chromeos.bin" || exit 2
echo "===> Updating..."
sudo chromeos-update -f "$workdir/$(echo $brunch_url | grep -o "[^/]*$")" -r "$workdir/chromeos.bin"
echo "===> Done!"
echo "---> Cleaning up..."
sudo rm -rf "$workdir"
